#!/bin/bash

#set -x

PIDFILE="$HOME/.docker-tor.pid"
PROXYPORT=58118
SOCKSPORT=59050


running() {
  test -e $PIDFILE &&
  docker ps | grep "$(cat $PIDFILE)" >/dev/null
}

start() {
  if ! running; then
    pid=$(docker run -d -p $PROXYPORT:8118 -p $SOCKSPORT:9050 frnksgr/tor)
    echo $pid > $PIDFILE
  fi
}

stop() {
  if running; then
    pid=$(cat $PIDFILE)
    docker kill $pid >/dev/null
    docker rm $pid >/dev/null
    rm $PIDFILE
  fi
}

help() {
  echo "Usage: $(basename $0) [start|stop]"
  echo "  start stop TOR server"
  echo "  proxy localhost:$PROXYPORT, socks-5 localhost:$SOCKSPORT"
}

case "$1" in
  "start")
    start
    ;;
  "stop")
    stop
    ;;
  *)
    help
    ;;
esac
